# Importing Numpy

In [1]:
import numpy as np

# Array:


In [2]:
a = np.array([1,23,34])   #1D array/vector

In [3]:
a

array([ 1, 23, 34])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [7]:
b = np.array([[1,2.5,3,4],
            [5,6,7,8]])

In [8]:
b

array([[1. , 2.5, 3. , 4. ],
       [5. , 6. , 7. , 8. ]])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.shape

(2, 4)

In [11]:
b.ndim

2

In [12]:
c = np.array([[1,2,3,4],
             [2,3,4,5],
             [3,4,5,6]])


In [13]:
c

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [14]:
d = np.array([[[4,3,2,1],
               [5,4,3,2],
               [6,5,4,3]],
    
              [[7,6,5,4],
               [8,7,6,5],
               [9,8,7,6]]])

In [15]:
d

array([[[4, 3, 2, 1],
        [5, 4, 3, 2],
        [6, 5, 4, 3]],

       [[7, 6, 5, 4],
        [8, 7, 6, 5],
        [9, 8, 7, 6]]])

In [16]:
c.shape, d.shape

((3, 4), (2, 3, 4))

In [17]:
c.ndim, d.ndim

(2, 3)

In [18]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int32'), dtype('float64'), dtype('int32'), dtype('int32'))

In [19]:
a.size, b.size, c.size, d.size

(3, 8, 12, 24)

In [20]:
a.nbytes, b.nbytes, c.nbytes,d.nbytes

(12, 64, 48, 96)