# Array Creation:


In [20]:
import numpy as np

In [21]:
e = np.zeros((2,2), dtype = 'float')

In [22]:
e

array([[0., 0.],
       [0., 0.]])

In [23]:
f = np.ones((3,2), dtype = 'int')

In [24]:
f

array([[1, 1],
       [1, 1],
       [1, 1]])

In [25]:
g = np.full((4,5), 7)

In [26]:
g

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [27]:
i = np.identity(4)

In [28]:
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
j = np.eye(3,4,-2)

In [30]:
j

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [31]:
k = np.arange(2,14,3)

In [32]:
k

array([ 2,  5,  8, 11])

In [33]:
l = np.linspace(1,9,20, dtype = 'float')

In [34]:
l

array([1.        , 1.42105263, 1.84210526, 2.26315789, 2.68421053,
       3.10526316, 3.52631579, 3.94736842, 4.36842105, 4.78947368,
       5.21052632, 5.63157895, 6.05263158, 6.47368421, 6.89473684,
       7.31578947, 7.73684211, 8.15789474, 8.57894737, 9.        ])

In [35]:
m = np.empty((2,5), dtype = 'int')

In [36]:
m

array([[    4128860,     6029375,     3801155,     5570652,     6619251],
       [    7536754,     5505116,           0, -1661596368,         474]])

In [37]:
for i in range(3):
    m[:,i] = i
m

array([[          0,           1,           2,     5570652,     6619251],
       [          0,           1,           2, -1661596368,         474]])