# Array Indexing:

In [1]:
import numpy as np

In [2]:
n= np.array([2,5,6,8,9])

In [3]:
n

array([2, 5, 6, 8, 9])

In [4]:
n[0]

2

In [5]:
n[2]

6

In [6]:
n[-2]

8

In [7]:
o = np.random.randint(5,15, size= (4,5))

In [8]:
o

array([[11,  5, 10, 10,  6],
       [10, 10,  6, 11, 10],
       [ 9, 14,  7, 10, 12],
       [11,  6, 14,  7,  6]])

In [9]:
o[0][2]

10

In [10]:
o[1][4]

10

In [11]:
o[1,2]

6

In [12]:
o[3,2]

14

In [13]:
p = np.random.randint(0,9, size=(3,3,4))

In [14]:
p

array([[[2, 7, 3, 1],
        [8, 0, 6, 1],
        [0, 7, 5, 8]],

       [[5, 0, 2, 5],
        [5, 5, 4, 3],
        [4, 4, 2, 4]],

       [[4, 3, 5, 3],
        [5, 3, 6, 6],
        [3, 2, 3, 5]]])

In [15]:
p[0,1,3]

1

In [16]:
p[1,2,0]

4

In [17]:
p[2,1,2]

6