# Array Slicing:

In [1]:
import numpy as np

In [2]:
n= np.array([2,5,6,8,9])

In [3]:
n

array([2, 5, 6, 8, 9])

In [4]:
n[0:4]

array([2, 5, 6, 8])

In [5]:
n[:3]

array([2, 5, 6])

In [6]:
n[1:]

array([5, 6, 8, 9])

In [7]:
o = np.random.randint(5,15, size= (4,5))

In [8]:
o

array([[14,  6, 12, 14, 13],
       [13, 14, 11,  9,  5],
       [12, 10,  6, 13, 11],
       [ 5,  6, 14, 13, 12]])

In [9]:
o[0:2,0:3]

array([[14,  6, 12],
       [13, 14, 11]])

In [10]:
o[1:3,2:4]

array([[11,  9],
       [ 6, 13]])