# Reshape:


In [2]:
import numpy as np

In [3]:
p = np.random.randint(1,8, size = (3,4))

In [4]:
p

array([[6, 1, 3, 5],
       [5, 4, 6, 3],
       [5, 3, 1, 2]])

In [5]:
p.reshape(4,3)

array([[6, 1, 3],
       [5, 5, 4],
       [6, 3, 5],
       [3, 1, 2]])

In [6]:
np.reshape(p,(4,3))

array([[6, 1, 3],
       [5, 5, 4],
       [6, 3, 5],
       [3, 1, 2]])

# Resize:


In [7]:
np.resize(p,(4,4))

array([[6, 1, 3, 5],
       [5, 4, 6, 3],
       [5, 3, 1, 2],
       [6, 1, 3, 5]])

In [8]:
q = np.resize(p,(4,5))

In [9]:
q

array([[6, 1, 3, 5, 5],
       [4, 6, 3, 5, 3],
       [1, 2, 6, 1, 3],
       [5, 5, 4, 6, 3]])

In [10]:
np.resize(p,(4,3))

array([[6, 1, 3],
       [5, 5, 4],
       [6, 3, 5],
       [3, 1, 2]])