# Ravel:


In [1]:
import numpy as np

In [2]:
r = np.random.randint(2,8, (3,4))

In [3]:
r

array([[5, 2, 7, 2],
       [6, 2, 5, 5],
       [4, 5, 3, 3]])

In [4]:
hello = r.ravel()

In [5]:
hello

array([5, 2, 7, 2, 6, 2, 5, 5, 4, 5, 3, 3])

In [6]:
hello[4]=10

In [7]:
hello

array([ 5,  2,  7,  2, 10,  2,  5,  5,  4,  5,  3,  3])

In [9]:
r                               #return a view of the array

array([[ 5,  2,  7,  2],
       [10,  2,  5,  5],
       [ 4,  5,  3,  3]])

# Flatten:


In [10]:
r

array([[ 5,  2,  7,  2],
       [10,  2,  5,  5],
       [ 4,  5,  3,  3]])

In [11]:
hi = r.flatten()

In [12]:
hi

array([ 5,  2,  7,  2, 10,  2,  5,  5,  4,  5,  3,  3])

In [13]:
hi[1] = 6

In [14]:
hi

array([ 5,  6,  7,  2, 10,  2,  5,  5,  4,  5,  3,  3])

In [16]:
r                                     #return a copy of the array, alaway alocates the memory.

array([[ 5,  2,  7,  2],
       [10,  2,  5,  5],
       [ 4,  5,  3,  3]])

##Shape:

In [17]:
r.shape = (4,3)

In [18]:
r

array([[ 5,  2,  7],
       [ 2, 10,  2],
       [ 5,  5,  4],
       [ 5,  3,  3]])