# Horizontal Stack:

In [1]:
import numpy as np

In [2]:
s = np.arange(2,11).reshape(3,3)

In [3]:
s

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
t = s+2

In [5]:
t

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
u = np.hstack((s,t))

In [7]:
u

array([[ 2,  3,  4,  4,  5,  6],
       [ 5,  6,  7,  7,  8,  9],
       [ 8,  9, 10, 10, 11, 12]])

In [8]:
v = np.column_stack((s,t))

In [9]:
v

array([[ 2,  3,  4,  4,  5,  6],
       [ 5,  6,  7,  7,  8,  9],
       [ 8,  9, 10, 10, 11, 12]])

In [10]:
w = np.concatenate((s,t), axis = 1)

In [11]:
w

array([[ 2,  3,  4,  4,  5,  6],
       [ 5,  6,  7,  7,  8,  9],
       [ 8,  9, 10, 10, 11, 12]])

In [13]:
w.shape = (3,6)

# Vertical Stack:

In [14]:
x = np.vstack((s,t))

In [15]:
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
y = np.row_stack((s,t))

In [17]:
y

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
z = np.concatenate((s,t), axis = 0)

In [19]:
z

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Depth Stack:

In [20]:
a = np.dstack((s,t))

In [21]:
a

array([[[ 2,  4],
        [ 3,  5],
        [ 4,  6]],

       [[ 5,  7],
        [ 6,  8],
        [ 7,  9]],

       [[ 8, 10],
        [ 9, 11],
        [10, 12]]])

In [22]:
s,t

(array([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))